### ISSUE TITLE
[REVIEW]: A course on Geographic Data Science

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#42]
**Submitting author:** @darribas (<a href="http://orcid.org/0000-0002-6274-1619">Daniel Arribas-Bel</a>)
**Repository:** <a href="https://github.com/darribas/gds18" target ="_blank">https://github.com/darribas/gds18</a>
**Version:** v4.1
**Editor:** @labarba
**Reviewer:** @lheagy, @jsta
**Archive:** <a href="https://doi.org/10.5281/zenodo.2650534" target="_blank">10.5281/zenodo.2650534</a>

## Status

[![status](http://jose.theoj.org/papers/ab5b87ff724fbdb2fda35a7301eecce9/status.svg)](http://jose.theoj.org/papers/ab5b87ff724fbdb2fda35a7301eecce9)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/ab5b87ff724fbdb2fda35a7301eecce9"><img src="http://jose.theoj.org/papers/ab5b87ff724fbdb2fda35a7301eecce9/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/ab5b87ff724fbdb2fda35a7301eecce9/status.svg)](http://jose.theoj.org/papers/ab5b87ff724fbdb2fda35a7301eecce9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/darribas/gds18" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lheagy & @jsta, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source for this learning module available at the <a target="_blank" href="https://github.com/darribas/gds18">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of a standard license? (OSI-approved for code, Creative Commons for content)
- [x] **Version:** v4.1
- [x] **Authorship:** Has the submitting author (@darribas) made visible contributions to the module? Does the full list of authors seem appropriate and complete?

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this module and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies?
- [x] **Usage:** Does the documentation explain how someone would adopt the module, and include examples of how to use it?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the module 2) Report issues or problems with the module 3) Seek support

### Pedagogy / Instructional design (Work-in-progress: reviewers, please comment!)

- [x] **Learning objectives:** Does the module make the learning objectives plainly clear? (We don't require explicitly written learning objectives; only that they be evident from content and design.)
- [x] **Content scope and length:** Is the content substantial for learning a given topic? Is the length of the module appropriate?
- [x] **Pedagogy:** Does the module seem easy to follow? Does it observe guidance on cognitive load? (working memory limits of 7 +/- 2 chunks of information)
- [x] **Content quality:** Is the writing of good quality, concise, engaging? Are the code components well crafted? Does the module seem complete?
- [x] **Instructional design:** Is the instructional design deliberate and apparent? For example, exploit worked-example effects; effective multi-media use; low extraneous cognitive load.

### JOSE paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Does the paper clearly state the need for this module and who the target audience is?
- [x] **Description:** Does the paper describe the learning materials and sequence?
- [x] Does it describe how it has been used in the classroom or other settings, and how someone might adopt it?
- [x] Could someone else teach with this module, given the right expertise?
- [x] Does the paper tell the "story" of how the authors came to develop it, or what their expertise is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source for this learning module available at the <a target="_blank" href="https://github.com/darribas/gds18">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of a standard license? (OSI-approved for code, Creative Commons for content)
- [x] **Version:** v4.1
- [x] **Authorship:** Has the submitting author (@darribas) made visible contributions to the module? Does the full list of authors seem appropriate and complete?

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this module and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies?
- [x] **Usage:** Does the documentation explain how someone would adopt the module, and include examples of how to use it?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the module 2) Report issues or problems with the module 3) Seek support

### Pedagogy / Instructional design (Work-in-progress: reviewers, please comment!)

- [x] **Learning objectives:** Does the module make the learning objectives plainly clear? (We don't require explicitly written learning objectives; only that they be evident from content and design.)
- [x] **Content scope and length:** Is the content substantial for learning a given topic? Is the length of the module appropriate?
- [x] **Pedagogy:** Does the module seem easy to follow? Does it observe guidance on cognitive load? (working memory limits of 7 +/- 2 chunks of information)
- [x] **Content quality:** Is the writing of good quality, concise, engaging? Are the code components well crafted? Does the module seem complete?
- [x] **Instructional design:** Is the instructional design deliberate and apparent? For example, exploit worked-example effects; effective multi-media use; low extraneous cognitive load.

### JOSE paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Does the paper clearly state the need for this module and who the target audience is?
- [x] **Description:** Does the paper describe the learning materials and sequence?
- [x] Does it describe how it has been used in the classroom or other settings, and how someone might adopt it?
- [x] Could someone else teach with this module, given the right expertise?
- [x] Does the paper tell the "story" of how the authors came to develop it, or what their expertise is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by labarba** [comment]
@lheagy, @jsta  — Thank you for agreeing to review for JOSE! This is where the action happens: work your way through the review checklist, feel free to ask questions or post comments here, and also open issues in the submission repository as needed. Godspeed!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00042/jose.00042/10.21105.jose.00042.pdf)

**Comment by lheagy** [comment]
Congrats on a really nice course @darribas! They are interesting examples and are well-explained. I have a few review comments, and once these are addressed I think it will be ready for publication

## review comments
- [ ] darribas/gds18#1: the repo license (cc-by-nc-sa) is different than the license stated in the README and on the website (cc-by) (@labarba, does JOSE have any concerns with the 'NC' portion of the license as it is [not considered "Free Cultural Work"](https://creativecommons.org/share-your-work/public-domain/freeworks)?)   
- [ ] darribas/gds18#10: there is no version information in the github repository 
- [ ] darribas/gds18#9: community guidelines. I did not see these anywhere in the repo
- [ ] darribas/gds18#7: a suggestion on simplifying the process for downloading data in the labs. Right now, the learner has to follow at least 2 links to get to the data from the notebook in most cases; this overhead could be reduced so there is less startup time for the labs. 


### minor fixes (not publication blockers in my opinion)
- [ ] darribas/gds18#6: installation instructions `conda activate` is preferred over `source activate`
- [ ] darribas/gds18#8: it looks like the api of pysal changed, so a couple of the labs error on import 

## feedback on the review process
- the paper criteria `Does the paper tell the "story" of how the authors came to develop it, or what their expertise is?` is a bit vague to me. I quite like the paper heading "Experience of use" used by @darribas and think that this captures the spirit of this criteria. So it might be worth considering that language as a bold-faced title for this bullet-point

**Comment by jsta** [comment]
This paper and course material looks quote good to me. I focused my review on the `labs` portion of the repository. In addition to the comments by @lheagy, I had several ideas for improvement:

# review comments

* Does the conda file specify all the dependencies including ones required for the optional excercises? (https://github.com/darribas/gds18/issues/2)

# minor fixes

* In the lab01 notebook, dropping columns is shown using both `del foo` and `pandas.drop` syntax. Consider only using panadas syntax to decrease cognative load?

* The paper states that the target audience is learners with little to no prior knowledge. Maybe text to this effect could be added to the `Overview` page?

* There are multiple instances where an operation is claimed to be simple or easy. I would recommend not emphasizing this so much as it can de-motivate people who are struggling.

* The default data path is highly variable among notebooks. Maybe these could be made consistent? (https://github.com/darribas/gds18/issues/3)

**Comment by darribas** [comment]
@jsta: I've addressed your minor fix.2 in #2157538de5fa10f74eb53652aeb72bfbed0afcf5

**Comment by darribas** [comment]
@jsta: on your minor fix.1, a bit of context: `del foo` and `pandas.drop` do not the same thing exactly. The former removes "in-place" while the latter creates a copy without the columns dropped. Both are useful in different contexts. Based on that, I've decided not to change it. However, I added a bit more of text to illustrate the differences and make them come out more clearly ([d4d8e522f14fce5ebe09f3f5bced20ce3f9eb289](https://github.com/darribas/gds18/commit/d4d8e522f14fce5ebe09f3f5bced20ce3f9eb289)).

**Comment by darribas** [comment]
@jsta: on your minor fix.3, I've just gone over every notebook and [replaced/removed](https://github.com/darribas/gds18/compare/d4d8e522f14fce5ebe09f3f5bced20ce3f9eb289...585899888fa13329606e11a5bd4a3f6bc1ec9f24) any instance of "simple", "easy", and "trivial". This has been an incredible wake-up to how the language can influence the student's attitude. I think it's a lot better now. Thanks!

**Comment by darribas** [comment]
Hello @lheagy and @jsta, I have looked at your issues about the links and access to the data ([`#3`](https://github.com/darribas/gds18/issues/3) and [`#7`](https://github.com/darribas/gds18/issues/7). Very good points both. A few thoughts and things I have(n't) done:

- There is one case (ie. Twitter dataset in Lab 9) where the license of the data does not allow public repackaging. In those cases, I'm hosting it on a private site for students only.
- There are several cases where the datasets come from a portal ([CDRC data](https://data.cdrc.ac.uk/)) that requires a free login to download datasets. I would like keep these cases as they are because:
     a) Those logins are used for statistics reported back to the funding body of the portal so I think it is important to give credit instead of downloading once and linking to the Github repo (effectively repackaging data).
     b) I think it is also important from the pedagogical point of view that the student gets some experience in accessing "real-world" data in the way they would have to if they were looking for data outside a structured course
- In cases where the data is already repackaged (ie. in the `data` folder), I have updated the notebooks to illustrate how, in addition to reading the file locally if you have downloaded it, you can read it from the course website link. This is implemented in commits from [`7a767`](https://github.com/darribas/gds18/commit/7a7678606b09275fbd26d59fc396d7e0ba5c7381) to [`4f194`](https://github.com/darribas/gds18/commit/4f1945b71b58636e9133247c1f8d506ebb28c6ec).
- In response to @lheagy's suggestion to write a bespoke method to download it in the notebook, I've decided against it, although I think it can be a useful approach in other contexts. My main motivation for this is:
     a) The pedagogical argument mentioned above of "forcing" students to get out in the wild to access data
     b) My sense is the code, even if explicitly mentioned as optional, would feel too advanced and put off students somehow

**Comment by darribas** [comment]
@labarba, @lheagy, @jsta. THANK you very much for going over my paper and project. I really appreciate your insight and comments. I think I have addressed every comment. Where the reviewer had opened an issue, I've responded there; where there was a comment in this thread, I've responded accordingly too. I think that should cover all of your concerns but I'm more than happy to work further on aspects you consider need it. I'll wait for your response, and thank you very much again!

**Comment by labarba** [comment]
Hi everybody!

I see a couple of remaining unchecked items in the review lists. Can you all give me a quick update on your status? Thanks!

**Comment by lheagy** [comment]
Congrats on a great course @darribas! All good on my end @labarba 🎉

**Comment by jsta** [comment]
I checked the remaining items in my review list. I think the paper is good to go. :shipit:

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00042/jose.00042/10.21105.jose.00042.pdf)

**Comment by labarba** [comment]
¶1
conscutive >> typo: consecutive

¶2
Although the content presented is relevant… >> the content presented where? The point you're trying to make here is unclear. And perhaps you could start this paragraph with the second sentence. (Or, you might just delete the first sentence.)

**Comment by labarba** [comment]
https://github.com/darribas/gds18/pull/11

**Comment by labarba** [comment]
- [ ] https://github.com/darribas/gds18/pull/12

**Comment by labarba** [comment]
- [ ] https://github.com/darribas/gds18/pull/13

**Comment by labarba** [comment]
"Although the learning emphasis is placed first and foremost on the student, there is support provided mainly through two channels: within the lab, there is at least one instructor for every 15 students answering questions one-on-one or in small groups; beyond contact time, the class has access to an online discussion forum monitored by the course leader, where students are encouraged to post not only questions but also answers and responses both to other students and to their original enquiry, in case they solve it themselves."

This is one LONG sentence. (1) can you cut this up? (2) can you remove syntactic expletives? (there is, there are); (3) can you simplify? E.g., "the learning emphasis is placed first and foremost on the student"—is this hyperbole to say "student-centered"?

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.2307/1183338 is OK
- 10.1080/10618600.2017.1384734 is OK
- 10.1177/0160017607301605  is OK

MISSING DOIs

- None

INVALID DOIs

- ISBN:9781446287484 is INVALID
- ISBN:978-0-471-73545-8 is INVALID
- ISBN:9781526402349 is INVALID
- ISBN: 978-0-470-86413-5 is INVALID
- ISBN:0803922450 is INVALID
```

**Comment by labarba** [comment]
@darribas — You have some bad DOIs in your BibTex. Please check/fix.

**Comment by darribas** [comment]
Hello @labarba, thank you very much for the review! I've gone over your comments, and I think I've included them all. The only one I'm unsure is the one relating the DOIs. The ones that come as invalid are all books, so they don't technically have a DOI but a ISBN. Following [this](https://www.doi.org/factsheets/ISBN-A.html), I've tried to turn them into actionable ISBNs (ISBN-A), but not sure if with full success. If there's any guidance in the journal about how to deal with these, I'll be happy to follow it if what I've done doesn't work.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00042/jose.00042/10.21105.jose.00042.pdf)

**Comment by labarba** [comment]
These links are not resolving:

https://doi.org/10.978.0471/735458
https://doi.org/10.978.08039/22450
https://doi.org/10.978.0470/864135
https://doi.org/10.978.14462/87484

If the reference doesn't have a DOI, then don't provide a DOI.

**Comment by darribas** [comment]
Thanks very much @labarba. I've just removed the failing DOIs with [8a83b98](https://github.com/darribas/gds18/commit/8a83b9814f8eaaf4c13133aa08fc95622ee97983). Let me know if there's anything else I should do.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00042/jose.00042/10.21105.jose.00042.pdf)

**Comment by labarba** [comment]
@darribas — Before we publish your JOSE paper, we'll need: 1) a new tagged release; please report the version number here, and 2) an archival deposit in Zenodo, Figshare or a similar service; please report the archive DOI here.

**Comment by darribas** [comment]
Fantastic! Here it is:

[![DOI](https://zenodo.org/badge/145456898.svg)](https://zenodo.org/badge/latestdoi/145456898)

Let me know if I need to do anything else. Really looking forward to having this published, super excited!

**Comment by labarba** [comment]
Can you edit the metadata of the Zenodo deposit so the title and author list matches the paper? Thanks!

**Comment by labarba** [comment]
@whedon set v4.1 as version

**Comment by whedon** [comment]
OK. v4.1 is the version.

**Comment by darribas** [comment]
Done!

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2650534 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2650534" target="_blank">10.5281/zenodo.2650534</a> is the archive.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #42 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.2307/1183338 is OK
- 10.1080/10618600.2017.1384734 is OK
- 10.1177/0160017607301605  is OK

MISSING DOIs

- https://doi.org/10.1057/palgrave.dddmp.4350070 may be missing for title: Geodemographics, GIS and neighbourhood targeting
- https://doi.org/10.4135/9781412939591.n896 may be missing for title: Point pattern analysis

INVALID DOIs

- 10.978.1526/402349 is INVALID
```

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00042/jose.00042/10.21105.jose.00042.pdf)

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/31

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/31, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.2307/1183338 is OK
- 10.1080/10618600.2017.1384734 is OK
- 10.1177/0160017607301605  is OK

MISSING DOIs

- https://doi.org/10.1057/palgrave.dddmp.4350070 may be missing for title: Geodemographics, GIS and neighbourhood targeting
- https://doi.org/10.4135/9781412939591.n896 may be missing for title: Point pattern analysis

INVALID DOIs

- 10.978.1526/402349 is INVALID
```

**Comment by labarba** [comment]
Would you accept these little tweaks to your bib?

https://github.com/darribas/gds18/pull/14

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/32
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jose.00042](https://doi.org/10.21105/jose.00042)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @darribas, your JOSE paper is published! 🚀 

Tremendous gratitude go to our reviewers: @lheagy, @jsta — we can do this thanks to your contribution! 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00042/status.svg)](https://doi.org/10.21105/jose.00042)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00042">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00042/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00042/status.svg
   :target: https://doi.org/10.21105/jose.00042
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00042/status.svg)](https://doi.org/10.21105/jose.00042)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. 
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jose

**Comment by darribas** [comment]
Fantastic!!! THANK you very much @labarba for superb editorial work and @lheagy and @jsta for a terrific reviewing!

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
